spring:
  application:
    name: unifer-discovery-1
eureka:
  client:
    service-url :
      defaultZone : ${EUREKA_SERVER/eureka:http://localhost:8761/eureka}
    register-with-eureka: false
    fetch-registry: false
